// Typed HTTP client for the SafetySignal API.
//
// baseUrl is `/api`, which Vite's dev-server proxy forwards to the backend
// (see vite.config.ts). This keeps the frontend code free of host URLs.
//
// `paths` comes from schema.ts, generated by `npm run gen:api` against
// the backend's live /openapi.json. Regenerate after backend API changes.

import createClient from 'openapi-fetch'
import type { paths } from './schema'

export const api = createClient<paths>({ baseUrl: '/api' })
