/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/drugs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Drugs
         * @description List all curated drugs with their total report counts.
         */
        get: operations["list_drugs_drugs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drugs/{drug_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Drug
         * @description Get full detail for one drug, including date range of reports.
         */
        get: operations["get_drug_drugs__drug_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drugs/{drug_id}/signals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Drug Signals
         * @description Return PRR-ranked adverse-event signals for this drug.
         */
        get: operations["get_drug_signals_drugs__drug_id__signals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/signals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Signals
         * @description Return top PRR-ranked safety signals across all drugs in the database.
         */
        get: operations["list_signals_signals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/adverse_events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Adverse Events
         * @description List adverse-event terms, ordered by total report count descending.
         */
        get: operations["list_adverse_events_adverse_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AdverseEventOut
         * @description One row in the GET /adverse_events list.
         */
        AdverseEventOut: {
            /** Id */
            id: number;
            /** Meddra Pt */
            meddra_pt: string;
            /** Meddra Soc */
            meddra_soc?: string | null;
            /** Report Count */
            report_count: number;
        };
        /**
         * AdverseEventSummary
         * @description An AE, minimal form. Embedded in signal responses.
         */
        AdverseEventSummary: {
            /** Meddra Pt */
            meddra_pt: string;
            /** Meddra Soc */
            meddra_soc?: string | null;
        };
        /**
         * ContingencyOut
         * @description 2x2 contingency table cells for one (drug, AE) pair.
         *
         *     a = this drug AND this AE
         *     b = this drug AND other AEs
         *     c = other drugs AND this AE
         *     d = other drugs AND other AEs
         */
        ContingencyOut: {
            /** A */
            a: number;
            /** B */
            b: number;
            /** C */
            c: number;
            /** D */
            d: number;
        };
        /**
         * DrugDetailOut
         * @description GET /drugs/{id} response. Adds date-range metadata.
         */
        DrugDetailOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Rxnorm Id */
            rxnorm_id?: string | null;
            /** Atc Class */
            atc_class?: string | null;
            /** Therapeutic Area */
            therapeutic_area: string;
            /**
             * Report Count
             * @description Total reports mentioning this drug as a suspect drug
             */
            report_count: number;
            /** First Report Date */
            first_report_date?: string | null;
            /** Last Report Date */
            last_report_date?: string | null;
        };
        /**
         * DrugOut
         * @description One row in the GET /drugs list.
         */
        DrugOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Rxnorm Id */
            rxnorm_id?: string | null;
            /** Atc Class */
            atc_class?: string | null;
            /** Therapeutic Area */
            therapeutic_area: string;
            /**
             * Report Count
             * @description Total reports mentioning this drug as a suspect drug
             */
            report_count: number;
        };
        /**
         * DrugSummary
         * @description A drug, minimal form. Embedded in cross-drug signal responses.
         */
        DrugSummary: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /**
         * ErrorOut
         * @description Shape of error responses (404, etc.). Matches what FastAPI's HTTPException emits.
         */
        ErrorOut: {
            /** Detail */
            detail: string;
        };
        /**
         * GlobalSignalOut
         * @description A signal across all drugs. Used by GET /signals — includes the drug.
         */
        GlobalSignalOut: {
            ae: components["schemas"]["AdverseEventSummary"];
            /**
             * Report Count
             * @description Number of reports linking this drug to this AE (= contingency.a)
             */
            report_count: number;
            /** Prr */
            prr: number;
            contingency: components["schemas"]["ContingencyOut"];
            drug: components["schemas"]["DrugSummary"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * SignalOut
         * @description One signal for a known drug. Used by GET /drugs/{id}/signals.
         *
         *     The drug is implicit from the URL, so it's not repeated in the body.
         */
        SignalOut: {
            ae: components["schemas"]["AdverseEventSummary"];
            /**
             * Report Count
             * @description Number of reports linking this drug to this AE (= contingency.a)
             */
            report_count: number;
            /** Prr */
            prr: number;
            contingency: components["schemas"]["ContingencyOut"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_drugs_drugs_get: {
        parameters: {
            query?: {
                /** @description Filter by therapeutic area (e.g. 'ssri_snri', 'statin'). */
                therapeutic_area?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DrugOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_drug_drugs__drug_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                drug_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DrugDetailOut"];
                };
            };
            /** @description Drug not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_drug_signals_drugs__drug_id__signals_get: {
        parameters: {
            query?: {
                min_prr?: number;
                min_count?: number;
                limit?: number;
            };
            header?: never;
            path: {
                drug_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalOut"][];
                };
            };
            /** @description Drug not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_signals_signals_get: {
        parameters: {
            query?: {
                min_prr?: number;
                min_count?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlobalSignalOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_adverse_events_adverse_events_get: {
        parameters: {
            query?: {
                /** @description Filter by MedDRA System Organ Class (currently always null). */
                soc?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdverseEventOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
