"""create initial tables

Revision ID: f9e9d0f9b956
Revises: 
Create Date: 2026-05-13 01:06:42.838594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9e9d0f9b956'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adverse_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meddra_pt', sa.Text(), nullable=False),
    sa.Column('meddra_soc', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meddra_pt')
    )
    op.create_table('drugs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('rxnorm_id', sa.Text(), nullable=True),
    sa.Column('atc_class', sa.Text(), nullable=True),
    sa.Column('therapeutic_area', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('reports',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('openfda_report_id', sa.Text(), nullable=False),
    sa.Column('drug_id', sa.Integer(), nullable=False),
    sa.Column('ae_id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Numeric(), nullable=True),
    sa.Column('sex', sa.Text(), nullable=True),
    sa.Column('report_date', sa.Date(), nullable=True),
    sa.Column('serious', sa.Boolean(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ae_id'], ['adverse_events.id'], ),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('openfda_report_id', 'drug_id', 'ae_id', name='uq_reports_report_drug_ae')
    )
    op.create_index('idx_reports_ae', 'reports', ['ae_id'], unique=False)
    op.create_index('idx_reports_drug', 'reports', ['drug_id'], unique=False)
    op.create_index('idx_reports_drug_ae', 'reports', ['drug_id', 'ae_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_reports_drug_ae', table_name='reports')
    op.drop_index('idx_reports_drug', table_name='reports')
    op.drop_index('idx_reports_ae', table_name='reports')
    op.drop_table('reports')
    op.drop_table('drugs')
    op.drop_table('adverse_events')
    # ### end Alembic commands ###
